apiVersion: v1
kind: Pod
metadata:
  name: nginx-create
  namespace: dafienz
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
