apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dafienz
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    NodePort: 30023
  type: NodePort
